const button1 = document.querySelector("#button1");
const button2 = document.querySelector("#button2");
const nameText = document.querySelector("#nameText");

button1.onclick = generateVintageName;
button2.onclick = generateModernName;

function getRandomInt(max) {
  return Math.floor(Math.random() * max);
}

function generateVintageName() {
  nameText.innerHTML = vintage[getRandomInt(vintage.length)];
}

function generateModernName() {
  nameText.innerHTML = modern[getRandomInt(modern.length)];
}

const vintage = [
  "Xx_sealteamkeef_xX",
  "Xx_imfiringmalaser_xX",
  "xXx_SwaggySmoker420_xXx",
  "Xx_DankedOut69_xX",
  "Shad0wSnipe420",
  "ePIC_420DankSmoker",
  "69MonsterSwag_xXx",
  "1337SkunkBlaze",
  "xXx_ePIC_420MaryJane",
  "DankStoner_69",
  "SwaggedOut_1337",
  "420BigBoss_xXx",
  "ePiC_DopeSniper",
  "xXx_69WeedMonster",
  "Dank1337Swaggy",
  "Xx_hornystoner420_xX",
];

const modern = [
  "Za Za Binks",
  "Jar Jar Doinks",
  "Jar Of Danks",
  "Jah Jah Danks",
  "Bud Lightyear",
  "BackWoody",
  "ZaZurg",
  "Grabba The Hutt",
  "Grabba The Nugg",
  "Blaze I",
  "XBONG-Wing",
  "High Fighter",
  "Marijuanium Falcon",
  "Spliff Destroyer",
  "Ventilator-Class Spliff Destroyer",
  "Revenge of the Spliff",
  "The Scarlett Spliff",
  "Iron Xan",
  "Pack Panther",
  "Loud Voldesnort",
  "Billsmokes Baggins",
  "Ron Weedsley",
  "Bongald Weedsley",
  "Fried Weedsley",
  "Purpy Weedsley",
  "Hairynug Potter",
  "Shakeo Malfoy",
  "Doobiedore",
  "Hoggsweed",
  "The Sorcerers Stoned",
  "And the Half-Baked Prince",
  "Hashgrid",
  "Dabrig",
  "Hashrig",
  "Cruikdanks",
  "Luna Lovesthatgoodgood",
  "Neville Bongtgrottle",
  "Neville Longbonghit",
  "Hermione Ganja",
  "Prisoner of Azkabong",
  "Prisoner of Zazakaban",
  "Albus Dumbledabs",
  "Albus Doobiedore",
  "Dia-ganj Alley",
  "Cedric Dabbedie",
  "Cedric Dooberie",
  "Vapor of Secrets",
  "Vaper of Sickspliffs",
  "Goblet of Fire",
  "Dabfoot",
  "Bongs",
  "And the Half-Nug Spliff",
  "Sirius Wax",
  "Professor McBonggagle",
  "Avada Cababsrig",
  "Severus Vape",
  "Indiana Jones and the Coil of Doom",
  "Temple of Doobs",
  "And the Kingdom of the Crystal Bong",
  "The Dial of Dankweed",
  "The Dial of Destiweed",
  "Jar Jar Spliffs",
  "Lando Cannabissian",
  "Darth Hitthisshit",
  "Ahsmoka Bongo",
  "Count Doobie",
  "Return of the Red Eyes",
  "Return of the Jedhigh",
  "Star Wars Episode 420: A New Dope",
  "Episode 5: The Empire Sparks Up",
  "The Edibles Strike Back",
  "The Empire Smokes Hash",
  "Admiral Dabbar",
  "Admiral Packbar",
  "Admiral Ashbar",
  "Grand Moff Tokin",
  "Count Dabula",
  "Dabsferatu",
  "Highlo Ren",
  "Salacious Weed Crumbs",
  "Bobo Fett",
  "Ganja Fett",
  "Danko Fett",
  "Luke Highwalker",
  "Luke Skunksmoker",
  "Dankakin Smokebonger",
  "Emperherb Palaptine",
  "Emperherb Nicotine",
  "Princess Leia Organic",
  "Bong Solo",
  "Laced Windu",
  "Kushyyyk",
  "Danktooine",
  "Darth Vapor",
  "Darth Vaper",
  "Dabman And Bongin",
  "The Toker",
  "Two-Faded",
  "The Scaresmoke",
  "The Scarecronic",
  "The Middler",
  "Poison Ivy",
  "Mr. Treeze",
  "Master Keef",
  "Tony Skunk",
  "Ganko Fett",
];
